# Site settings
title: Jekyll Seed
safe:           false
source:         app
exclude:
  - assets/scripts
  - assets/vendor
  - assets/styles
  - README.md
timezone: America/New_York
highlighter: false 

baseurl: ""

collections:
  sections:
    output: true
